@startuml
participant Client
participant RESTAPI
participant ObjectService
database KVStore
participant StorageService
database Filesystem

Client -> RESTAPI: PUT /bucket/object
RESTAPI -> Client: 100 Continue
Client -> RESTAPI: Object 
RESTAPI -> ObjectService: Put Object
ObjectService -> ObjectService: Calculate hash
ObjectService -> ObjectService: Generate object ID
ObjectService -> ObjectService: Generate object parts
ObjectService -> ObjectService: Encode object parts
ObjectService -> ObjectService: Distribute parts
ObjectService -> StorageService: Persist object parts
StorageService -> Filesystem: Write object parts to disk
ObjectService -> KVStore: Store object metadata
RESTAPI -> Client: 200 OK
@enduml
